/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Entrada;

/**
 *
 * @author gutie
 */
public class Entrada extends javax.swing.JFrame {

    /**
     * Creates new form Entrada
     */
    public Entrada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        IngresoAdmin = new javax.swing.JPanel();
        RegresarUsuario = new javax.swing.JLabel();
        AyudaAdmin = new javax.swing.JLabel();
        UsuarioAdmin = new javax.swing.JTextField();
        IngresarAdmin = new javax.swing.JButton();
        OjoVisibleAdmin = new javax.swing.JLabel();
        ContraseñaAdmin = new javax.swing.JPasswordField();
        IconoAdmin = new javax.swing.JLabel();
        OjoNoVisibleAdmin = new javax.swing.JLabel();
        Verificacion = new javax.swing.JPanel();
        ImagenDeIconoVerificacion = new javax.swing.JLabel();
        NombreVerificacion = new javax.swing.JTextField();
        ApellidoVerificacion = new javax.swing.JTextField();
        DniVerificacion = new javax.swing.JTextField();
        IngresoVerificacion = new javax.swing.JButton();
        AyudaVerificacion = new javax.swing.JLabel();
        regresarAlUsuario = new javax.swing.JLabel();
        IngresoUsuario = new javax.swing.JPanel();
        UsuarioCentral = new javax.swing.JTextField();
        IngresoDeUsuario = new javax.swing.JButton();
        IngresoaVentanaAdmin = new javax.swing.JLabel();
        OjoVisibleUsuarioPRincipal = new javax.swing.JLabel();
        OjoNoVisibleUsuarioPRincipal = new javax.swing.JLabel();
        ContraseñaPrincipal = new javax.swing.JPasswordField();
        IconoimagendEfondoUsuario = new javax.swing.JLabel();
        ayudaUsario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegresarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegresarUsuario.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                RegresarUsuarioAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                RegresarUsuarioAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        RegresarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarUsuarioMouseClicked(evt);
            }
        });

        AyudaAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AyudaAdmin.setForeground(new java.awt.Color(153, 0, 0));
        AyudaAdmin.setText("¿Olvidaste tu contraseña?");
        AyudaAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        UsuarioAdmin.setBackground(new java.awt.Color(255, 204, 204));
        UsuarioAdmin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        UsuarioAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioAdminActionPerformed(evt);
            }
        });

        IngresarAdmin.setBackground(new java.awt.Color(153, 0, 0));
        IngresarAdmin.setForeground(new java.awt.Color(255, 255, 255));
        IngresarAdmin.setText("INICIAR SECION");
        IngresarAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        ContraseñaAdmin.setText("ingresedfsdfsfdf");
        ContraseñaAdmin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTRASEÑA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        OjoNoVisibleAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout IngresoAdminLayout = new javax.swing.GroupLayout(IngresoAdmin);
        IngresoAdmin.setLayout(IngresoAdminLayout);
        IngresoAdminLayout.setHorizontalGroup(
            IngresoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresoAdminLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(IngresoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AyudaAdmin)
                    .addGroup(IngresoAdminLayout.createSequentialGroup()
                        .addGroup(IngresoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsuarioAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContraseñaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(IngresoAdminLayout.createSequentialGroup()
                                .addComponent(IngresarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(RegresarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(IngresoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OjoVisibleAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OjoNoVisibleAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(IconoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        IngresoAdminLayout.setVerticalGroup(
            IngresoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresoAdminLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(IngresoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IngresoAdminLayout.createSequentialGroup()
                        .addComponent(UsuarioAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ContraseñaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(IngresoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IngresarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegresarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(IngresoAdminLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(IngresoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OjoVisibleAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OjoNoVisibleAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(IconoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(AyudaAdmin)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.add(IngresoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));

        Verificacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Verificacion.add(ImagenDeIconoVerificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 160, 140));

        NombreVerificacion.setBackground(new java.awt.Color(255, 255, 255));
        NombreVerificacion.setForeground(new java.awt.Color(0, 0, 0));
        NombreVerificacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NOMBRE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        Verificacion.add(NombreVerificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 260, 50));

        ApellidoVerificacion.setBackground(new java.awt.Color(255, 255, 255));
        ApellidoVerificacion.setForeground(new java.awt.Color(0, 0, 0));
        ApellidoVerificacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "APELLIDO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        Verificacion.add(ApellidoVerificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 50));

        DniVerificacion.setBackground(new java.awt.Color(255, 255, 255));
        DniVerificacion.setForeground(new java.awt.Color(0, 0, 0));
        DniVerificacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DNI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        Verificacion.add(DniVerificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 260, 50));

        IngresoVerificacion.setBackground(new java.awt.Color(153, 0, 0));
        IngresoVerificacion.setForeground(new java.awt.Color(0, 0, 0));
        IngresoVerificacion.setText("VERIFICAR");
        IngresoVerificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Verificacion.add(IngresoVerificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 130, 30));

        AyudaVerificacion.setBackground(new java.awt.Color(255, 255, 255));
        AyudaVerificacion.setForeground(new java.awt.Color(153, 0, 0));
        AyudaVerificacion.setText("¿aun tiene problema de ingreso?");
        AyudaVerificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Verificacion.add(AyudaVerificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, 20));

        regresarAlUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Verificacion.add(regresarAlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 30, 30));

        jPanel3.add(Verificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 540, 290));

        IngresoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        IngresoUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsuarioCentral.setBackground(new java.awt.Color(255, 204, 204));
        UsuarioCentral.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        IngresoUsuario.add(UsuarioCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, 50));

        IngresoDeUsuario.setBackground(new java.awt.Color(153, 0, 0));
        IngresoDeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        IngresoDeUsuario.setText("INICIAR SECION");
        IngresoDeUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        IngresoUsuario.add(IngresoDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 130, 40));

        IngresoaVentanaAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IngresoaVentanaAdmin.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                IngresoaVentanaAdminAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                IngresoaVentanaAdminAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        IngresoaVentanaAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresoaVentanaAdminMouseClicked(evt);
            }
        });
        IngresoUsuario.add(IngresoaVentanaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 30, 30));

        OjoVisibleUsuarioPRincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IngresoUsuario.add(OjoVisibleUsuarioPRincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 30, 30));

        OjoNoVisibleUsuarioPRincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IngresoUsuario.add(OjoNoVisibleUsuarioPRincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 30, 30));

        ContraseñaPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTRASEÑA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        IngresoUsuario.add(ContraseñaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 200, 50));
        IngresoUsuario.add(IconoimagendEfondoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 70, 60));

        ayudaUsario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ayudaUsario.setForeground(new java.awt.Color(153, 0, 0));
        ayudaUsario.setText("¿Olvidaste tu contraseña?");
        ayudaUsario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IngresoUsuario.add(ayudaUsario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jPanel3.add(IngresoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 268, 306));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarUsuarioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_RegresarUsuarioAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_RegresarUsuarioAncestorAdded

    private void RegresarUsuarioAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_RegresarUsuarioAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_RegresarUsuarioAncestorMoved

    private void RegresarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarUsuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RegresarUsuarioMouseClicked

    private void IngresoaVentanaAdminAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_IngresoaVentanaAdminAncestorAdded

    }//GEN-LAST:event_IngresoaVentanaAdminAncestorAdded

    private void IngresoaVentanaAdminAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_IngresoaVentanaAdminAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresoaVentanaAdminAncestorMoved

    private void IngresoaVentanaAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresoaVentanaAdminMouseClicked

    }//GEN-LAST:event_IngresoaVentanaAdminMouseClicked

    private void UsuarioAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ApellidoVerificacion;
    public javax.swing.JLabel AyudaAdmin;
    public javax.swing.JLabel AyudaVerificacion;
    public javax.swing.JPasswordField ContraseñaAdmin;
    public javax.swing.JPasswordField ContraseñaPrincipal;
    public javax.swing.JTextField DniVerificacion;
    public javax.swing.JLabel IconoAdmin;
    public javax.swing.JLabel IconoimagendEfondoUsuario;
    public javax.swing.JLabel ImagenDeIconoVerificacion;
    public javax.swing.JButton IngresarAdmin;
    public javax.swing.JPanel IngresoAdmin;
    public javax.swing.JButton IngresoDeUsuario;
    public javax.swing.JPanel IngresoUsuario;
    public javax.swing.JButton IngresoVerificacion;
    public javax.swing.JLabel IngresoaVentanaAdmin;
    public javax.swing.JTextField NombreVerificacion;
    public javax.swing.JLabel OjoNoVisibleAdmin;
    public javax.swing.JLabel OjoNoVisibleUsuarioPRincipal;
    public javax.swing.JLabel OjoVisibleAdmin;
    public javax.swing.JLabel OjoVisibleUsuarioPRincipal;
    public javax.swing.JLabel RegresarUsuario;
    public javax.swing.JTextField UsuarioAdmin;
    public javax.swing.JTextField UsuarioCentral;
    public javax.swing.JPanel Verificacion;
    public javax.swing.JLabel ayudaUsario;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JLabel regresarAlUsuario;
    // End of variables declaration//GEN-END:variables
}
