/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista.Entrada;

/**
 *
 * @author gutie
 */
public class RegistroTrabajdores extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroDeUsuario
     */
    public RegistroTrabajdores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombresUsario = new javax.swing.JTextField();
        apellidosUsuario = new javax.swing.JTextField();
        edadUsuario = new javax.swing.JTextField();
        telefonoUsuario = new javax.swing.JTextField();
        idUsuario = new javax.swing.JTextField();
        correoUsuario = new javax.swing.JTextField();
        direccionUsuario = new javax.swing.JTextField();
        generoUsuario = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuario = new javax.swing.JTable();
        guardarRegistroUsuario = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombresUsario.setBackground(new java.awt.Color(204, 255, 255));
        nombresUsario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombres", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        nombresUsario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombresUsarioActionPerformed(evt);
            }
        });
        getContentPane().add(nombresUsario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 230, 60));

        apellidosUsuario.setBackground(new java.awt.Color(204, 255, 255));
        apellidosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        getContentPane().add(apellidosUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 240, 60));

        edadUsuario.setBackground(new java.awt.Color(204, 255, 255));
        edadUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        edadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(edadUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 120, 60));

        telefonoUsuario.setBackground(new java.awt.Color(204, 255, 255));
        telefonoUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        getContentPane().add(telefonoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, 170, 60));

        idUsuario.setEditable(false);
        idUsuario.setBackground(new java.awt.Color(204, 255, 255));
        idUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Codigo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        idUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(idUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 150, 60));

        correoUsuario.setBackground(new java.awt.Color(204, 255, 255));
        correoUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Correo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        getContentPane().add(correoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 266, 60));

        direccionUsuario.setBackground(new java.awt.Color(204, 255, 255));
        direccionUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dirección", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        getContentPane().add(direccionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 280, 60));

        generoUsuario.setBackground(new java.awt.Color(204, 255, 255));
        generoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));
        generoUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Género", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        getContentPane().add(generoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 164, 60));

        tablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaUsuario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 1050, -1));

        guardarRegistroUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        guardarRegistroUsuario.setText("Guardar");
        getContentPane().add(guardarRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 87, 130, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombresUsarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombresUsarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombresUsarioActionPerformed

    private void edadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadUsuarioActionPerformed

    private void idUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField apellidosUsuario;
    public javax.swing.JTextField correoUsuario;
    public javax.swing.JTextField direccionUsuario;
    public javax.swing.JTextField edadUsuario;
    public javax.swing.JComboBox<String> generoUsuario;
    public javax.swing.JButton guardarRegistroUsuario;
    public javax.swing.JTextField idUsuario;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField nombresUsario;
    public javax.swing.JTable tablaUsuario;
    public javax.swing.JTextField telefonoUsuario;
    // End of variables declaration//GEN-END:variables
}
